# Generated by Django 3.2.6 on 2021-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice1', '0002_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
