# Generated by Django 3.2.6 on 2021-08-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice1', '0004_auto_20210819_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=13, max_digits=15)),
                ('lng', models.DecimalField(decimal_places=13, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart_data',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_data',
            name='food_item',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='cart',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice1.food_item'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Just Deliver it'),
        ),
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='lng',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practice1.payment'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='landmark',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=13, default=None, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(decimal_places=13, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practice1.city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practice1.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practice1.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practice1.restaurant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='practice1.user'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'food_item'), name='unique user fooditem'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='practice1_cart',
        ),
        migrations.DeleteModel(
            name='Cart_Data',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice1.user'),
        ),
    ]
