# Generated by Django 3.2.6 on 2021-08-24 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice1', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingsAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_rating', models.IntegerField(choices=[(1, 'Worst'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('food_rating', models.IntegerField(choices=[(1, 'Worst'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('delivery_review', models.TextField(default='Not provided')),
                ('food_review', models.TextField(default='Not provided')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practice1.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practice1.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practice1.user')),
            ],
        ),
    ]
