# Generated by Django 3.2.6 on 2021-08-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice1', '0007_ratingsandreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('1', 'COD'), ('2', 'Debit/Credit'), ('3', 'UPI')], max_length=1),
        ),
    ]
